version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '07:00'
      timezone: 'Africa/Johannesburg'
    reviewers:
      - 'dominicgbauer'
    assignees:
      - 'dominicgbauer'
